### ISSUE TITLE
[BUG] dot run

### ISSUE THREAD

**Issue by CoolLiuzw** [uPagge/uBlogger#1]
PS E:\uBlogger\exampleSite> hugo serve
Start building sites …
WARN 2020/12/07 10:05:06

Current environment is "development". The "comment system", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "CDN" 和 "fingerprint" 不会启用.

ERROR 2020/12/07 10:05:27 Failed to get JSON resource "https://api.twitter.com/1/statuses/oembed.json?id=877500564405444608&dnt=true": Get "https://api.twitter.com/1/statuses/oembed.json?id=877500564405444608&dnt=true": dial tcp 74.86.151.167:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
Built in 21962 ms
Error: Error building site: logged 1 error(s)

**Comment by uPagge** [comment]
Do I understand correctly that this is windows 10?

What is your version of HUGO?

**Comment by uPagge** [comment]
And what happens if you open this link in your browser

https://api.twitter.com/1/statuses/oembed.json?id=877500564405444608&dnt=true

**Comment by CoolLiuzw** [comment]
good

**Comment by uPagge** [comment]
@CoolLiuzw You have covered the issue. The problem is no longer relevant?

**Comment by ErdemDegirmenci** [comment]
I also faced the same error.

Current environment is "development". The "comment system", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "CDN" 和 "fingerprint" 不会启用.

Built in 314 ms
Error: Error building site: TOCSS: failed to transform "css/style.scss" (text/x-scss). Check your Hugo installation; you need the extended version to build SCSS/SASS.

hugo version 
hugo v0.83.1-5AFE0A57 windows/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio

**Comment by uPagge** [comment]
@ErdemDegirmenci 

The solution to your problem is described in the error

“Check your Hugo installation; you need the extended version to build SCSS / SASS. "

You need an extended version of hugo
