### ISSUE TITLE
[BUG] Unable to build website

### ISSUE THREAD

**Issue by achenger** [uPagge/uBlogger#10]
### Describe the bug

When I execute `hugo server` at  _v0.79.1/extended windows/amd64_ ,

I copy the `config.toml` from `themes\uBlogger\exampleSite\`  ,
then show an error as follow.

BUT, when using [ Basic Configuration](https://ublogger.netlify.app/theme-documentation-basics/#basic-configuration) ,it's ok ,and just cannot show homepage (Other pages are normal)

### Screenshots

```shell
Start building sites …
WARN 2020/12/31 20:40:00

Current environment is "development". The "comment system", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "CDN" 和 "fingerprint" 不会启用.

ERROR 2020/12/31 20:40:01 render of "page" failed: execute of template failed: template: posts/single.html:131:16: executing "no-content" at <partial "single/footer.html" .>: error calling partial: "D:\youdef.com\themes\uBlogger\layouts\partials\single\footer.html:11:14": execute of template failed: template: partials/single/footer.html:11:14: executing "partials/single/footer.html" at <index .Site.Data.authors $authorName>: error calling index: index of untyped nil
ERROR 2020/12/31 20:40:01 render of "page" failed: execute of template failed: template: posts/single.html:131:16: executing "no-content" at <partial "single/footer.html" .>: error calling partial: "D:\youdef.com\themes\uBlogger\layouts\partials\single\footer.html:11:14": execute of template failed: template: partials/single/footer.html:11:14: executing "partials/single/footer.html" at <index .Site.Data.authors $authorName>: error calling index: index of untyped nil
ERROR 2020/12/31 20:40:01 render of "page" failed: execute of template failed: template: _default/single.html:34:16: executing "_default/single.html" at <partial "footer.html" .>: error calling partial: "D:\youdef.com\themes\uBlogger\layouts\partials\footer.html:36:30": execute of template failed: template: partials/footer.html:36:30: executing "partials/footer.html" at <index .Site.Data.authors $authorName>: error calling index: index of untyped nil
ERROR 2020/12/31 20:40:01 render of "home" failed: execute of template failed: template: index.html:36:20: executing "content" at <.Render>: error calling Render: "D:\youdef.com\content\posts\daohang.md:42:26": failed to execute template ["summary"] v: "D:\youdef.com\themes\uBlogger\layouts\_default\summary.html:42:26": execute of template failed: template: _default/summary.html:42:26: executing "_default/summary.html" at <index .Site.Data.authors $authorName>: error calling index: index of untyped nil
Built in 275 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:34:16: executing "_default/single.html" at <partial "footer.html" .>: error calling partial: "D:\youdef.com\themes\uBlogger\layouts\partials\footer.html:36:30": execute of template failed: template: partials/footer.html:36:30: executing "partials/footer.html" at <index .Site.Data.authors $authorName>: error calling index: index of untyped nil
```

### Build Environment

- OS: [Windows 10,]
- Theme version/commit [ ?how to see, maybe lastest ]
- Hugo version [v0.79.1/extended windows/amd64 ]

Please try to use Hugo **extended** version before opening the issue.

### Screenshot of homepage by using Basic Configuration
![image](https://user-images.githubusercontent.com/16396357/103411370-8e5e4b80-4baa-11eb-907d-18e0a10d1371.png)

**Comment by MarcinKlejna** [comment]
@achenger  it's not a bug here you have the solution

**Comment by achenger** [comment]
tks, I start the site lucky, 
but, there is no posts list in homepage, shown as:

(https://s3.ax1x.com/2020/12/31/rvc4kF.png)

```shell
   [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6 
```

**Comment by uPagge** [comment]
Do you have posts in the content folder?

**Comment by achenger** [comment]
Yes, I have posts. you can visit my site by (https://youdef.vercel.app/) , and building source is here: (https://github.com/achenger/youdef.com)

Thanks.

**Comment by achenger** [comment]
OK, I find the problems of that I add ex-catalog in content dir. Thanks.

**Comment by uPagge** [comment]
@achenger could you describe how you solved the problem in more detail

**Comment by uPagge** [comment]
I found how to fix the problem via config.

To do this, add
```
[params]
  mainSections = ["posts"]
```

**Comment by uPagge** [comment]
but for now there is an actual problem with tags, I will fix it in a week. #8 

For now, I recommend using tags

**Comment by achenger** [comment]
Yes, you are right.
I like putting other files or dir under `./content/`. (I used to like to use Hexo before, the platform allow the action.)

**I removed redundant files to `/static` , then solve it.** 
---
For: https://github.com/uPagge/uBlogger/issues/10#issuecomment-753290261  I will try your suggestion.

**Comment by achenger** [comment]
Finally, maybe I find a bug:
(https://s3.ax1x.com/2021/01/01/rzSgVP.png)

API requested image  didn't show normaly in https://youdef.vercel.app/, but the special image shown in http://localhost:1313/ .

So, what happened? We can talk about it.

**Comment by uPagge** [comment]
I can't help with so little data.

Everything works for me and there were no such problems, and your repository does not contain the current version of the site, there is no such post.

**Comment by achenger** [comment]
Got it , thanks for your guidance all the time.
