### ISSUE TITLE
Cant copy code to clipboard

### ISSUE THREAD

**Issue by underfarm** [uPagge/uBlogger#102]
Hi, 

I cant seem to get the "copy code to clipboard" function to work. Is it supposed to be a button in the corner for code blocks? I tried using:

  [params.page.code]
      # whether to show the copy button of the code block
      copy = true

in the config.toml, but it dident do anything. I also browsed the demo web app, but couldn't find functionality "copy to clipboard". Is this working as intended?

**Comment by uPagge** [comment]
I recently replaced the library that is responsible for highlighting the code.

In the new version of the documentation, everything will be described
