### ISSUE TITLE
[BUG] Emoji is shown as non-printable character 

### ISSUE THREAD

**Issue by sudipghimire533** [uPagge/uBlogger#105]
### Describe the bug

When I visited [emoiji support from homepage](https://ublogger.netlify.app/emoji-support/) the emoijis are not shown properly but instead are shown as rectangle box

### Expected behavior

Colorful emoji rendered instead of just rectangle box

### Screenshots

![image](https://user-images.githubusercontent.com/39845901/120577288-d4625880-c443-11eb-943c-9ef1deb648b1.png)

### Build Environment

- OS: Debian
- Theme version/commit [https://ublogger.netlify.app/]
- Hugo version: unspecified

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: Debian 10
- Browser: Brave 90.1

### Additional Information

I can accept that I have not installed any fonts with emoji support but you know those who will visit my site in future can't be expected to install font. So anything we cam do?

**Comment by uPagge** [comment]
![изображение](https://user-images.githubusercontent.com/40397740/120839528-b7c43e80-c571-11eb-9d39-fb570ddb48c8.png)

Everything works fine

**Comment by uPagge** [comment]
![изображение](https://user-images.githubusercontent.com/40397740/120839657-e2ae9280-c571-11eb-8403-aa8b2e3a9e18.png)

There may be a problem with the Brawe browser. There is nothing you can do about it. Emoticons are displayed differently for each browser

**Comment by sudipghimire533** [comment]
As I mentioned It did worked in windows based browser but not in my vanilla debian workstation but again did showed up in another ubuntu distro so I think it is someting to do with fonts. Am i wrong?
