### ISSUE TITLE
[BUG] Featured Images seem to HAVE to be called featured-image.<extension> in order to work

### ISSUE THREAD

**Issue by powershellpr0mpt** [uPagge/uBlogger#11]
### Describe the bug

I have tried featured images in various options, with random names, various yaml tags, when not called featured-image.<extension> it will cause the image to produce a broken link, even when using Page Resources as described.

### Expected behavior

`featuredImage: picture.jpg`

or 
```
resources:
- name: "picture"
  src: "picture.jpg"
```

should display the Featured Image `picture.jpg`

Instead, it ONLY works when naming it featured-image.<extension>

### Build Environment

- OS: Windows 10 Enterprise [2004/19041.685]
- Theme version/commit 1.1.0
- Hugo version Hugo Static Site Generator v0.79.1/extended windows/amd64

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: Windows 10 Enterprise [2004/19041.685]
- Browser Edge Chromium

**Comment by MarcinKlejna** [comment]
For me, in addition to the entry:
```
resources:
- name: "featured-image"
  src: "featured-image.png"
```
The page doesn't rebuild I get this error:
Rebuild failed:
```
"/blog/content/posts/grav-debian/index.md:8:1": failed to unmarshal YAML: yaml: line 7: did not find expected '-' indicator
```

**Comment by MarcinKlejna** [comment]
For me, in addition to the entry:
```
resources:
- name: "featured-image"
  src: "featured-image.jpg"
```
The page doesn't rebuild I get this error:
```
/blog/content/posts/grav-debian/index.md:8:1": failed to unmarshal YAML: yaml: line 7: did not find expected '-' indicator
```

**Comment by uPagge** [comment]
Thanks for the message, I will study how you will have free time

**Comment by uPagge** [comment]
I researched your question

You cannot change the name field - it must always be featured-image. This allows the template to understand that this picture is being used for a preview. Only the src field changes.

For example so

```yaml
resources:
- name: "featured-image"
  src: "ssh_config.jpg"
```

I checked this option works

**Comment by uPagge** [comment]
However, there really is a problem with the featuredImage variable, I will try to solve it in the next version.

**Comment by nareshganesan** [comment]
@uPagge Thanks for your awesome work! 

Is there a way to have a featured image specific to light/dark mode? Not sure if this is in the roadmap.

**Comment by uPagge** [comment]
@nareshganesan I’ll think if this can be implemented, it’s better to create a separate issue feature so that I don’t forget about it))

**Comment by nareshganesan** [comment]
@uPagge I have raised an issue.
