### ISSUE TITLE
[BUG] Images won't load

### ISSUE THREAD

**Issue by FenryrMKIII** [uPagge/uBlogger#123]
### Describe the bug

Images don't load. Altough they are located both in `assets` and in `static`.

```
![my_name](safari-pinned-tab.svg)
```

The site is hosted on AWS so it's not an issue of local hosting. It seems the address of the picture is not correctly resolved e.g. the site shows : 

```
https://master.d2ge0bljxmpk20.amplifyapp.com/post_sub_folder/safari-pinned-tab.svg
```

instead of 

```
https://master.d2ge0bljxmpk20.amplifyapp.com/static/safari-pinned-tab.svg
```

Plus, the post URL itself is not correct as it should be : 

```
https://master.d2ge0bljxmpk20.amplifyapp.com/content/posts/post_sub_folder/post/safari-pinned-tab.svg
```

### Expected behavior

Images should load.

### Screenshots

Not applicable

### Build Environment

- OS: [e.g. Windows 10, macOS, Ubuntu]
- Theme version/commit [e.g. 0.2.0, 2ccba79]
- Hugo version [e.g. 0.69.0]

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: Windows 10
- Browser Chrome

### Additional Information

Configuration files or front matter code...

**Comment by uPagge** [comment]
as far as I remember hugo doesn't support svg as well as jpg or png.  to add svg you need to write your own handler
