### ISSUE TITLE
[FEATURE] ability or documentation to change colour scheme

### ISSUE THREAD

**Issue by powershellpr0mpt** [uPagge/uBlogger#13]
### Describe the feature you want

- Ability to change colour scheme (or at least background/font colour) for light & dark mode, ideally through config.toml
- Provide documentation on how to change this otherwise

**Comment by MarcinKlejna** [comment]
@powershellpr0mpt You can change colors by editing `/assets/css/_override.scss` and `_custom.scss`
https://ublogger.netlify.app/theme-documentation-basics/#33-style-customization

Here you have my changes for example: https://gitlab.com/marcin-klejna/blog/-/tree/master/assets/css
result: https://notatnik.netlify.app/

**Comment by uPagge** [comment]
I don't even know what to add to @MarcinKlejna's words

We should write more about this in the documentation.

**Comment by uPagge** [comment]
@MarcinKlejna Comments are activated on your site, but they are not. Perhaps this is some kind of bug or you just did not have time to configure them?

![изображение](https://user-images.githubusercontent.com/40397740/103531575-b1367b80-4e9a-11eb-9efa-136ad19d0543.png)

**Comment by MarcinKlejna** [comment]
@uPagge No time, there is nothing to comment on there :)
