### ISSUE TITLE
[BUG] Font awesome is not load on your document page

### ISSUE THREAD

**Issue by chinkung** [uPagge/uBlogger#136]
### Describe the bug

Font awesome is not load on your document page.

### Expected behavior

Please see LoveIt document screenshot.

### Screenshots

LoveIt document (https://hugoloveit.com/about/)
![image](https://user-images.githubusercontent.com/2522806/132752431-8ead37ce-8482-49c1-8d1d-60f9fb09f342.png)

uBlogger document (https://ublogger.netlify.app/about/)
![image](https://user-images.githubusercontent.com/2522806/132752271-0223a9c3-0fd5-419b-ac8a-7aa694cf566e.png)

**Comment by uPagge** [comment]
In one of the release notes, I explained why I removed font awesome, this is not a bug, but a feature. In short, font awesome is suitable for rapid prototyping, but not for serious development, more than 80% of the user-loaded styles from font awesome you will not use, this is terrible

**Comment by chinkung** [comment]
@uPagge 
Thanks for clarification, I think it would be great if document will be refactored to make it update and easier to read.

I see some features from LoveIt such as lightgallery has been removed in ublogger but still show in ublogger document https://ublogger.netlify.app/theme-documentation-content/
