### ISSUE TITLE
[BUG] Gists aren't showing indents

### ISSUE THREAD

**Issue by mfcollins3** [uPagge/uBlogger#14]
### Describe the bug

I'm trying to embed code fragments from GitHub Gists using the built-in gist short code. The Gist is rendering, but it is not showing indents. All of the text is left justified. It appears to be happening on the demo site too: https://ublogger.netlify.app/theme-documentation-built-in-shortcodes/#2-gist

### Expected behavior

The Gist should show with proper indents.

### Screenshots

<img width="1730" alt="gist" src="https://user-images.githubusercontent.com/104274/103559662-bd5b1280-4e73-11eb-8532-18641d24ff17.png">

### Build Environment

- OS: macOS
- Theme version/commit 1.2.0
- Hugo version 0.80.0

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: macOS
- Browser: Chrome, Safari

**Comment by uPagge** [comment]
Hello

Unfortunately, this is a legacy from a past project. I'll try to figure out what's the matter, but unlikely in the next version.

Perhaps closer to February

**Comment by uPagge** [comment]
Fixed and already added to master
