### ISSUE TITLE
Problem when I modify config.toml

### ISSUE THREAD

**Issue by MrAntooo** [uPagge/uBlogger#19]
Hi, 
first of all I congratulate you on having updated my favorite theme in an exceptional way.
When I finish editing config.toml and start with "hugo serve" it gives me the following errors:

1)
`ERROR 2021/01/13 14:14:14 render of "taxonomy" failed: execute of template failed: template: taxonomy/terms.html:34:16: executing "taxonomy/terms.html" at <partial "footer.html" .>: error calling partial: "C:\Users\vitos\Documents\antonioas.com\themes\uBlogger\layouts\partials\footer.html:36:30": execute of template failed: template: partials/footer.html:36:30: executing "partials/footer.html" at <index .Site.Data.authors $authorName>: error calling index: index of untyped nil`

2)
`ERROR 2021/01/13 14:14:14 render of "home" failed: execute of template failed: template: index.html:34:16: executing "index.html" at <partial "footer.html" .>: error calling partial: "C:\Users\vitos\Documents\antonioas.com\themes\uBlogger\layouts\partials\footer.html:36:30": execute of template failed: template: partials/footer.html:36:30: executing "partials/footer.html" at <index .Site.Data.authors $authorName>: error calling index: index of untyped nil
Built in 154 ms`

3)
`Error: Error building site: failed to render pages: render of "taxonomy" failed: execute of template failed: template: taxonomy/terms.html:34:16: executing "taxonomy/terms.html" at <partial "footer.html" .>: error calling partial: "C:\Users\vitos\Documents\antonioas.com\themes\uBlogger\layouts\partials\footer.html:36:30": execute of template failed: template: partials/footer.html:36:30: executing "partials/footer.html" at <index .Site.Data.authors $authorName>: error calling index: index of untyped nil`

Surely the cause of this error is me who am inexperienced because this is the second time I try another Hugo theme.

Thank you for your availability.

**Comment by uPagge** [comment]
Hello

This is not a bug. I have changed the structure and approach to attribution. Described in more detail in the documentation :)

https://ublogger.netlify.app/theme-documentation-content/#author
