### ISSUE TITLE
[BUG] parse failed: template: shortcodes/admonition.html:4: function "merge" not defined

### ISSUE THREAD

**Issue by long5778013** [uPagge/uBlogger#20]
parse failed: template: shortcodes/admonition.html:4: function "merge" not defined

**Comment by uPagge** [comment]
This data is not enough to understand the problem.

**Comment by long5778013** [comment]
> This data is not enough to understand the problem.

What I've done is :
1. git submodule init (uBlogger)
2. git submodule update or pull uBlogger
3. hugo server -D
and the result is the logging: themes/uBlogger/layouts/shortcodes/admonition.html:4:1": parse failed: template: shortcodes/admonition.html:4: function "merge" not defined

Thx for ur assistance :P

**Comment by uPagge** [comment]
Hmm, this is weird. Please select your operating system and HUGO version

**Comment by long5778013** [comment]
> Hmm, this is weird. Please select your operating system and HUGO version

OS I'm using now(in my home) is MacOS bigsur 11.0.1 and hugo version is [Hugo Static Site Generator v0.79.1/extended darwin/amd64 BuildDate: unknown]. On this computer the site generation is totally OK.

This computer'OS is different from the other one I was using. Pls wait for about 12 hours. I'll give you new feedback. Thx.

**Comment by long5778013** [comment]
It's hugo version 0.55.5's bad. Sorry to bother.

**Comment by uPagge** [comment]
Nothing wrong. If you have any questions, please contact :)
