### ISSUE TITLE
[BUG] Share to HackerNews doesn't work

### ISSUE THREAD

**Issue by tstenhaug** [uPagge/uBlogger#25]
### The problem

When trying to enable sharing posts to HackerNews by way of e.g.

```
[params.page.share]
enable = true
Twitter = true
Facebook = true
HackerNews = true
```
it doesn't add a button for sharing to HackerNews.

### Expected behavior

I expect a share to HackerNews icon/link to appear at the bottom of the post, along with other buttons.

### Screenshots

![image](https://user-images.githubusercontent.com/22069/104922542-288c0500-599b-11eb-89f8-5958130e6b0f.png)

### Build Environment

- OS: Arch Linux
- Theme version/commit: addce327
- Hugo version: 0.80.0

### Preview Environment

- OS: Arch Linux
- Browser: Chromium  87.0.4280.141

**Comment by uPagge** [comment]
Fixed, will be available in the next release. The fixes are already in the dev branch.
