### ISSUE TITLE
[BUG] TOC does not always render correctly

### ISSUE THREAD

**Issue by embano1** [uPagge/uBlogger#26]
### Describe the bug

The static TOC is not always correctly rendered when resizing the screen or viewing the page on a tablet, e.g. iPad Pro 11 in landscape mode (works fine in portrait mode orientation). See the following three screenshots:

Normal view:

![image](https://user-images.githubusercontent.com/15986659/105044787-6b1b1380-5a67-11eb-8983-3cf4308f14de.png)

Resize window a bit so dynamic TOC disappears and static TOC appears. Note that the content does not show in the TOC (bug):

![image](https://user-images.githubusercontent.com/15986659/105044860-7ff7a700-5a67-11eb-9e7b-7dbe3a8aabb8.png)

Resize a bit more until eventually the TOC will correctly show up:

![image](https://user-images.githubusercontent.com/15986659/105044918-96056780-5a67-11eb-9725-fc6e3585e48b.png)

### Expected behavior

LoveIt theme does not show this behavior, i.e. immediately shows static TOC at some point with full content.

### Screenshots

See above.

### Build Environment

Used the live reference from https://ublogger.netlify.app/theme-documentation-built-in-shortcodes/

### Preview Environment

Used the live reference from https://ublogger.netlify.app/theme-documentation-built-in-shortcodes/

### Additional Information

Configuration files or front matter code...

**Comment by uPagge** [comment]
Yes you are right. I have already fixed this on the dev branch. Expect next release :)

**Comment by embano1** [comment]
Awesome!

**Comment by farhan443** [comment]
Was looking forward into this, thanks for the follow up!
