### ISSUE TITLE
[FEATURE] use HTML format in markdown

### ISSUE THREAD

**Issue by jtxiaocom** [uPagge/uBlogger#27]
# I use raw HTML in markdown, hugo doesn't render.
I use  `<img src="https://static-1257291176.cos.ap-hongkong.myqcloud.com/pic/1610098201732.jpg" alt="1610098201732" style="zoom:50%;" />` to zoom picture.

This is display properly in Typora, but not in website.
![image](https://user-images.githubusercontent.com/58872525/105132459-ea6f1c80-5b25-11eb-944f-40ee5b923570.png)
![image](https://user-images.githubusercontent.com/58872525/105132427-dfb48780-5b25-11eb-852e-ca16cb4a3090.png)

Is it possiable to render raw HTML?

**Comment by uPagge** [comment]
I don't quite understand the problem. I pasted html on my site and it just added a picture.

You can send the sources

**Comment by jtxiaocom** [comment]
I am sorry, when I read hugo official document, I realized that I need to set "unsafe = true" in [markup.goldmark.renderer].

Thank you for your patience

reference: https://gohugo.io/getting-started/configuration-markup/

**Comment by uPagge** [comment]
yes, I also thought about hugo config but was looking for something like htmlTrue :)
