### ISSUE TITLE
[BUG] Comment frame not in the center 

### ISSUE THREAD

**Issue by long5778013** [uPagge/uBlogger#28]
### Describe the bug

I enabled comment like gitalk or telegram-comment, when rendered to the page, the comment frame not in the center.

### Expected behavior

The comment frame should in the center..

### Screenshots

![image](https://user-images.githubusercontent.com/10125514/106127058-1e3ae980-6199-11eb-9eea-add453b0a0db.png)

### Build Environment

- OS: [macOS 10.15.6 (19G2021)]
- Theme version/commit [1.3.X master newest]
- Hugo version [e.g.v0.79.1]

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: [e.g. macOS]
- Browser [e.g. Chrome, Safari]

**Comment by uPagge** [comment]
It seems to me that I have already fixed this, but just haven't released it yet.

Check if the problem is with the dev branch?

**Comment by panniyuyu** [comment]
I found the same problem, how can I solve it?

**Comment by uPagge** [comment]
@panniyuyu It seems to me that I have already fixed this, but just haven't released it yet.

Check if the problem is with the dev branch?

**Comment by panniyuyu** [comment]
But the problem does not seem to be resolved when i checkout dev branch.🤕

**Comment by uPagge** [comment]
@panniyuyu Okay, I'll see what's wrong and let you know

**Comment by yqchilde** [comment]
I use valine comments, and mine is not in the middle of the screen either.

**Comment by uPagge** [comment]
@yqchilde Yes, I remember this problem. I was going to deal with her soon

**Comment by uPagge** [comment]
I have released a fix to the master, can anyone confirm that the problem has been fixed?

**Comment by yqchilde** [comment]
The test is fine. Thank you for your work.
