### ISSUE TITLE
[BUG] archetypes/default.md tags and categories default values crash

### ISSUE THREAD

**Issue by Esgariot** [uPagge/uBlogger#29]
### Describe the bug

Following tutorial and adding first page by
```sh
hugo new posts/first_post.md
```
results in error.

![image](https://user-images.githubusercontent.com/6072243/106128439-af8d6a00-615f-11eb-91c6-f2865a8a2f45.png)

 Changing `archetypes/default.md`, lines 16 and 17 values `[""]` to `[]` and re-creating post fixes the error.

commit d8e0d9c51da9a15cb9ce538bbec68af07174f595 introduced the bug, by changing `[]` to `[""]` in `archetypes/default.md`

### Expected behavior

Adding new post with default archetypes (inferred from uBlogger theme) should work and not crash

### Screenshots

![image](https://user-images.githubusercontent.com/6072243/106128459-b4521e00-615f-11eb-869d-1cfb0972de65.png)

### Build Environment

- OS: `Windows10/WSL1`
- Theme version/commit `addce327bafbe7991baf2897def687b23a1864aa themes/uBlogger (1.3.0-2-gaddce32)`
- Hugo version `Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: unknown`

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: Windows 10
- Browser: Firefox

### Additional Information

If I have time I'll create PR later :)

**Comment by uPagge** [comment]
I will fix this in the next release. The fix is already available in dev
