### ISSUE TITLE
[FEATURE] GDPR compliance

### ISSUE THREAD

**Issue by gorootde** [uPagge/uBlogger#30]
### Describe the feature you want

- Disable font loading from any CDN (e.g. fonts.gstatic.com) via configuration property
- In general being able to disable any communication to hosts other than the one hosting the website

Only thing I saw in the network console was fonts.gstatic.com and fonts.googleapis.com so far. Not sure wether there is anything else.

### Useful reference

According to GDPR it is not allowed to send personal data to anybody, unless the user has given consent. As this is not possible for fonts (before page is loaded!) all assets need to be self-hosted.

**Comment by uPagge** [comment]
It is not entirely clear how this is related to fonts. You do not give any user data, you download fonts, how can this violate the GDPR?

**Comment by gorootde** [comment]
The IP address of the user alone is considered to be personal data. By loading fonts and other assets from 3rd party servers, it is exposed. See https://complianz.io/google-fonts-and-gdpr-does-it-work/ and various other sources on the internet. Google for "Google fonts gdpr"

**Comment by Admonstrator** [comment]
There are some JS CDNs for libraries as well - but I would not call them dangerous for GDPR violation so far.
Google Fonts is easy to resolve by deleting the line starting with ``/@import url`` in ``_ublogger.scss`` 

(Or by replacing them for local font storage)

**Comment by uPagge** [comment]
I removed this font from the next version so that the GDPR is no longer violated
