### ISSUE TITLE
[BUG] Wrong blockquote

### ISSUE THREAD

**Issue by long5778013** [uPagge/uBlogger#33]
### Describe the bug

Wrong effect of markdown's '>'blockquote.

### Expected behavior

Words after '>' should be blockquoted.

### Screenshots
![image](https://user-images.githubusercontent.com/10125514/106573366-7ea0a100-6574-11eb-94dc-204d9d79d03c.png)

**Comment by uPagge** [comment]
I don't quite understand what the bug is. This is a feature))

more details here

https://github.com/uPagge/uBlogger/releases/tag/1.3.0
