### ISSUE TITLE
Whitespace in admonition layout causes rendering error

### ISSUE THREAD

**Issue by RylandDeGregory** [uPagge/uBlogger#34]
These two whitespace lines are breaking admonitions.

https://github.com/uPagge/uBlogger/blob/addce327bafbe7991baf2897def687b23a1864aa/layouts/shortcodes/admonition.html#L20
https://github.com/uPagge/uBlogger/blob/addce327bafbe7991baf2897def687b23a1864aa/layouts/shortcodes/admonition.html#L26

Without whitespace lines:
<img width="845" alt="Screen Shot 2021-02-04 at 11 30 21 AM" src="https://user-images.githubusercontent.com/18073815/106923828-7794a280-66dc-11eb-960b-6124ad2be9c0.png">

With whitespace lines: 
<img width="849" alt="Screen Shot 2021-02-04 at 11 30 30 AM" src="https://user-images.githubusercontent.com/18073815/106923780-6e0b3a80-66dc-11eb-9a6f-53a322092ad8.png">

**Comment by uPagge** [comment]
Thanks, fixed in dev. Expect in the next release
