### ISSUE TITLE
[BUG] [TOC] Unable to nest heading beyond 2 level

### ISSUE THREAD

**Issue by farhan443** [uPagge/uBlogger#38]
### Describe the bug

The Table of Content (TOC) outlines the headings as written in the markdown / HTML.  However, this is only true for up to 2 level nesting. Beyond that, the TOC stops outlining them. 

### Expected behavior

I expected headings beyond level 2 to be displayed in the TOC. 

#### Source Code:
![Screenshot_20210216_162405](https://user-images.githubusercontent.com/77048921/108044740-39e92f80-7075-11eb-8363-10fce47c6250.png)

#### Output:
![Screenshot_20210216_164016](https://user-images.githubusercontent.com/77048921/108045197-c136a300-7075-11eb-8107-4d88b0555677.png)

![Screenshot_20210216_164032](https://user-images.githubusercontent.com/77048921/108045215-c562c080-7075-11eb-8736-dd62325dc766.png)

#### Expected Output:
![Screenshot_20210216_163951](https://user-images.githubusercontent.com/77048921/108045234-cb58a180-7075-11eb-9a53-ebaa15894b36.png)

### Build Environment

- OS: Ubuntu 20.04 LTS
- Theme version: 1.3.0 (Latest)
- Hugo version:  v0.80.0-extended

### Preview Environment

- OS: Ubuntu 20.04 LTS
- Browser: Chromium 88.0.4324.150

### Additional Information

I wish the issue ends here, but it's not. It creates another problem if you insist on nesting heading beyond 2 level. I'll start a new issue for it. 

----
The screenshot is produced from a freshly installed Hugo site, with a freshly installed uBlogger theme.

**Comment by uPagge** [comment]
It has nothing to do with the topic. This is controlled by the Hugo settings.
```yaml
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
```

**Comment by farhan443** [comment]
> It has nothing to do with the topic. This is controlled by the Hugo settings.

My bad, you absolutely correct. I'm sorry. I should have known.

**Comment by farhan443** [comment]
> config.yaml:
> 
> ```yaml
> markup:
>   tableOfContents:
>     startLevel: 2
>     endLevel: 6
> ```

Works perfectly, thanks a lot.
