### ISSUE TITLE
[BUG] [TOC] Incorrect heading is highlighted if you nest beyond 2 level

### ISSUE THREAD

**Issue by farhan443** [uPagge/uBlogger#39]
### Describe the bug

This is an additional issue caused by #38 

The wide-screen TOC (the one displayed at the top-right) highlights the heading you're currently on. Which is a nice feature to have. However, if there is a heading nested under the heading you're currently in, the next eligible heading will be displayed instead.  For this to happen, your current heading has to be level 2, and the next heading has to be level 3.  

Note: the eligible heading to be displayed in the TOC are level 1 and level 2 nested. See #38 for detail. 

### Expected behavior

It should highlight the correct heading, which is the one you're currently in. 

#### Source Code:
![Screenshot_20210216_171722](https://user-images.githubusercontent.com/77048921/108049680-2fca2f80-707b-11eb-88a7-9b5316cb2c80.png)

1.1 is level 1
1.2 is nested to 1.1 (level 2)
3.1 is nested to 2.1 (level 3)

The same goes with 2.2, 2.2 and 3.2 

#### Output:

![Screenshot_20210216_171830](https://user-images.githubusercontent.com/77048921/108050031-ab2be100-707b-11eb-87e6-6f750992ddaa.png)
3.1 is nested under 2.1, which means we're still on heading or section 2.1 However, the TOC shows otherwise. They highlighted the next eligible heading. Which is a level 1 heading (1.2).

The problem continues when we scroll down a bit:
![Screenshot_20210216_171944](https://user-images.githubusercontent.com/77048921/108050432-28575600-707c-11eb-86ca-a3bb60824cc8.png)
We're still on 3.1, yet the TOC highlighted 2.2, jumped 2 headings.  

### Build Environment
OS: Ubuntu 20.04 LTS
Theme version: 1.3.0 (Latest)
Hugo version: v0.80.0-extended

### Preview Environment
OS: Ubuntu 20.04 LTS
Browser: Chromium 88.0.4324.150

### Additional Information

The screenshot is produced from a freshly installed Hugo site, with a freshly installed uBlogger theme.

**Comment by uPagge** [comment]
Dublicate #21

**Comment by farhan443** [comment]
> Dublicate #21 

My bad. I'm sorry, I should've been more careful.
