### ISSUE TITLE
[BUG] Some problem...

### ISSUE THREAD

**Issue by MarcinKlejna** [uPagge/uBlogger#4]
Thank you for your work. When I add to config.toml
```
# Author config
[author]
name = "Marcin"
```

The page stops displaying, errors appear:
```
ERROR 2020/12/24 18:37:13 render of "page" failed: execute of template failed: template: posts/single.html:129:16: executing "no-content" at <partial "single/footer.html" .>: error calling partial: "/home/noiro/Projekty/Hugo projekty/test/themes/uBlogger/layouts/partials/single/footer.html:11:14": execute of template failed: template: partials/single/footer.html:11:14: executing "partials/single/footer.html" at <index .Site.Data.authors $authorName>: error calling index: index of untyped nil

```

Hugo Static Site Generator v0.79.1/extended linux/amd64

### Screenshots

(https://ibb.co/VNSM6Tx)
(https://ibb.co/8mJ69sV)

### Build Environment

- OS: Debian
- Theme version/commit 1.1.0

**Comment by uPagge** [comment]
Hi

This is not a bug. It has to do with the new implementation of authorship.

I hope I was able to detail how it works in the documentation :)

https://ublogger.netlify.app/theme-documentation-content/#author

If something is still not clear, please contact me
