### ISSUE TITLE
dark mode navbox grey not dark-grey

### ISSUE THREAD

**Issue by f-s** [uPagge/uBlogger#41]
Hi,

you nav-box in dark mode is actually grey and not dark-grey like the rest of the theme.

Thanks,

f-s

**Comment by uPagge** [comment]
Hello

It would be nice to look at screenshots of the problem

**Comment by f-s** [comment]
![image](https://user-images.githubusercontent.com/7151788/108370461-f91c2280-71fc-11eb-9eca-5ce9e2550b3b.png)

**Comment by uPagge** [comment]
These blocks will be changed in the next releases))

**Comment by f-s** [comment]
thanks!
