### ISSUE TITLE
inline TOC background not dark-grey but grey in dark mode

### ISSUE THREAD

**Issue by f-s** [uPagge/uBlogger#42]
Hi,

the collapsed inline TOC (eg. on small screen devices) is not dark-grey but grey in dark mode.

Thanks,

f-s

**Comment by uPagge** [comment]
Hello

It would be nice to look at screenshots of the problem

**Comment by f-s** [comment]
![image](https://user-images.githubusercontent.com/7151788/108370582-1ea92c00-71fd-11eb-91bf-a9cd51b0e6b9.png)

**Comment by uPagge** [comment]
I still don't understand what the problem is

**Comment by f-s** [comment]
the background colour is too bright compared to the rest of the themes background-colours in dark mode

**Comment by uPagge** [comment]
Understood well, I'll try to choose a less bright one))
