### ISSUE TITLE
[BUG] back and forward buttons are really really huge...

### ISSUE THREAD

**Issue by dan-m8t** [uPagge/uBlogger#43]
### Describe the bug
The back and forward buttons below each post are really huge in my case, not sure what went wrong

### Expected behavior

Smaller buttons :D

### Screenshots

![bigbutton](https://user-images.githubusercontent.com/48068660/108928188-152b2400-7642-11eb-8c0a-dc6da8fec010.png)

### Build Environment

- OS: Container running with podman (https://hub.docker.com/r/klakegg/hugo)
- Theme version/commit 1.3.0
- Hugo version [e.g. 0.69.0] 0.81.0

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: Fedora 33
- Browser Firefox, Brave Browser

### Additional Information

Configuration files or front matter code...

**Comment by uPagge** [comment]
Whoa, unexpected. But in the next version this block will change, so the problem should disappear by itself
