### ISSUE TITLE
Documentation error - social.yml vs. social.yaml

### ISSUE THREAD

**Issue by cmosetick** [uPagge/uBlogger#45]
uBlogger documentation uses the term `social.yaml` but the filename where social type items can be configured is currently named `social.yml` in this themes git repository.
Suggestion at this time is to just update the documentation to say social.yml.

Reference:
- line 829 `exampleSite/content/posts/theme-documentation-basics/index.en.md`
- https://github.com/uPagge/uBlogger/blob/master/assets/data/social.yml
- https://ublogger.netlify.app/theme-documentation-basics/#site-configuration

![Screen Shot 2021-02-26 at 3 25 32 PM](https://user-images.githubusercontent.com/4873085/109300362-76701480-7847-11eb-9090-35bc137bb482.png)

**Comment by cmosetick** [comment]
This PR https://github.com/uPagge/uBlogger/pull/46 resolves this issue.

**Comment by uPagge** [comment]
Thanks for your help, but the documentation is starting to lag behind reality quite a bit, and I almost see no point in editing

We plan to completely rewrite it in the near future.
