### ISSUE TITLE
[BUG] Images are not resizing depending on the device

### ISSUE THREAD

**Issue by lerra** [uPagge/uBlogger#47]
### Describe the bug

The images are not resizing to the user's device, the result is sliding option to the right for users to be able to see the full images.

### Expected behavior

Resized images fitted to the user's screen

### Screenshots

![image](https://user-images.githubusercontent.com/18061206/109387808-bbf21780-7903-11eb-8d6f-b0e289ef1c8a.png)
![image](https://user-images.githubusercontent.com/18061206/109387815-c7454300-7903-11eb-93dc-f1e7ebe4b7d1.png)

### Build Environment
I am using the github action to build it https://github.com/lerra/lezg.in/blob/master/.github/workflows/main.yml

- OS: Ubuntu 18.04
- Theme version/commit addce32
- Hugo version 0.71.1

### Preview Environment
https://lezg.in/

- OS: Android & Ubuntu
- Browser Chrome & Firefox

### Additional Information
https://github.com/lerra/lezg.in/blob/master/content/posts/adding-an-api-to-my-grind-and-brew-coffee-machine-to-make-it-smart/index.en.md
https://lezg.in/adding-an-api-to-my-grind-and-brew-coffee-machine-to-make-it-smart/

**Comment by uPagge** [comment]
You are using an outdated version of the theme.

Also, judging by your site, you have made multiple changes. If you open the documentation, you will see that everything works great in the original template.

https://ublogger.netlify.app/theme-documentation-extended-shortcodes/

**Comment by lerra** [comment]
Hi mate,

I solved my problem, it could be due to my setup or it could be others that may bump into the same issue. Either way, I want to share my finding.

It is the latest version of the theme (addce32 => https://github.com/lerra/lezg.in/tree/master/themes ) but I solved my problem by adding a width & height parameter to fit within the "minimum screen" or what to say. After that resizing to the user's device screen works. It's easy to reproduce, if its removed then no resizing is done.

Btw, creds for the theme, its awesome!

**Comment by uPagge** [comment]
@lerra Strange, but your summary is clearly not the last one.

Why don't you just use the Markdown syntax to insert images?

**Comment by lerra** [comment]
@uPagge What do yo mean? :-)

I tried to use the markdown syntax with the same result

**Comment by uPagge** [comment]
@lerra 
![изображение](https://user-images.githubusercontent.com/40397740/109615116-9011a480-7b44-11eb-86aa-2d211b10dbc8.png)

**Comment by lerra** [comment]
@uPagge hi mate, sorry, the reply on what do you mean was for "Strange, but your summary is clearly not the last one.".

The markdown syntax have been tested with unsuccessful result.

But as i said,it may be something with my setup but I still wanted to share the result of that would not be the case.

If you want I can create posts with markdown, img and figure if that helps.

Thanks again for a great theme!
