### ISSUE TITLE
[BUG] Mardown italics

### ISSUE THREAD

**Issue by MarcinKlejna** [uPagge/uBlogger#5]
italics does not work properly using * text * or _text_ highlights instead of using italics
https://ublogger.netlify.app/basic-markdown-syntax/#italics

**Comment by uPagge** [comment]
Hi
This is not a bug, this is a feature :D

I wanted to add this feature with text selection as a marker. I decided to sacrifice italic text as it is quite rare in my opinion.

P.S. I also had to sacrifice a standard quote ">".

**Comment by achenger** [comment]
enen, I think original standard quote ">" is greater :rofl:

**Comment by uPagge** [comment]
I am working on getting italic text back, but adding a selection with a marker

**Comment by uPagge** [comment]
Having studied all the possible options, I decided to leave it as it is.

Italic text is rarely needed, and highlighting is a great tool.

**Comment by MarcinKlejna** [comment]
if someone needs italics, he can use this:
https://gitlab.com/marcin-klejna/blog/-/blob/master/assets/css/_custom.scss#L10

i am not a programmer and i don't know css, i did it by trial and error :)

**Comment by uPagge** [comment]
@MarcinKlejna It's a good idea, maybe I'll make a switch in the next version that will return italic text for those who need it.

**Comment by farhan443** [comment]
> Having studied all the possible options, I decided to leave it as it is.
> 
> Italic text is rarely needed, and highlighting is a great tool.

I agree with you. For most people, it's probably won't be as crucial. But for those who strive to write in accordance with writing rules and grammar, it could be an issue. 

In my native language, it is a must to italicized any foreign words, at least to our own writing guide. It'll be nice if we can optionally revert to the default italic style. 

Don't worry, it's not a big deal for me. Good thing I know a bit of CSS to adjust it myself. Thanks for clarifying this up. I thought it was a bug :) 

>  It's a good idea, maybe I'll make a switch in the next version that will return italic text for those who need it.

That's cool. Thanks for reconsidering.
