### ISSUE TITLE
[BUG] Unable to override scss files

### ISSUE THREAD

**Issue by zeridon** [uPagge/uBlogger#51]
### Describe the bug
While playing woth the theme and tweaking a bit the content length i discovered that it is not possible to override the theme scss files.

### Expected behavior
NOTE: This behaviour is observed with the `ext` version of hugo
Hugo supports overriding parts of theme by placing them in your project in the corresponding directory. e.g. if you have `theme/uBlogger/assets/css/_uBlogger.scss` and you create a file `assets/css/_uBlogger.scss` its content should take precedence.

This does not happen due to `resources` folder being committed into the repo. REF: https://sammart.in/hugo-css-override-failure/

### Build Environment

- OS: linux (docker) image is `klakegg/hugo:ext-alpine` (at the moment 0.82)
- Theme version/commit: 1.3.0/addce32
- Hugo version: 0.82

**Comment by uPagge** [comment]
Hello

Thanks for your contribution to the project, but if you go to the dev branch, you will see that everything is fine there.

I checked and the override works in the dev branch. Unfortunately, I never got my hands on the release.

Moreover, I recommend that you add the resources folder to the git tracking, if on the server you clone your repository this will save you from re-generating files.

**Comment by zeridon** [comment]
Adding the resources has it's benefits but warants explicit mentioning :). Otherwise some people (like the unfortunate me) spend some time trying to figure out what happens :)

**Comment by uPagge** [comment]
@zeridon I will try to reflect this nuance in the new documentation :)
