### ISSUE TITLE
Blockquotes in Markdown didn't work well.

### ISSUE THREAD

**Issue by ieeetorin** [uPagge/uBlogger#55]
### Describe the bug

When I use `>` to quote some words, the markdown seems not to work well.

You can see the rendering result is very different from the LoveIt theme.

### Screenshots

<img width="983" alt="Screen Shot 2021-03-10 at 1 01 24 PM" src="https://user-images.githubusercontent.com/4992828/110579301-7c4beb00-81a1-11eb-993e-9e6e97191677.png">

<img width="1045" alt="Screen Shot 2021-03-10 at 1 07 25 PM" src="https://user-images.githubusercontent.com/4992828/110579348-95ed3280-81a1-11eb-9b57-7014dc5b412e.png">

### Build Environment

- OS: [e.g. macOS]
- Theme version/commit [e.g. 1.3.0]
- Hugo version [v0.81.0+extended]

### Preview Environment

- OS: [macOS]
- Browser [Chrome, Safari]

**Comment by ieeetorin** [comment]
Hello, @uPagge ,

Please see the above issue, I don't know how to get the quote pattern in a blue quote like in theme LoveIt.
Is it because the uBlogger theme? If yes, what should I do to use markdown theme in LoveIt.

Thank you very much.

Cheers

**Comment by uPagge** [comment]
Yes. This is not a bug, but a feature. 

For a quote, you can use admonition:
https://ublogger.netlify.app/theme-documentation-extended-shortcodes/#4-admonition

```
{{< admonition type=info >}}
blockquote
{{< /admonition >}}
```

![изображение](https://user-images.githubusercontent.com/40397740/110580556-fff1e180-8179-11eb-933b-f727ade8fa3b.png)

This view is already available in the dev branch and will appear in master in the next release.
