### ISSUE TITLE
[BUG] Building issue with new version

### ISSUE THREAD

**Issue by Warsasor** [uPagge/uBlogger#56]
### Describe the bug

Hi, I downloaded new update and my site can't run anymore don't know why....

### Expected behavior

Site loading correctly without error

### Screenshots

failed to render pages: render of "page" failed: execute of template failed: template: posts/single.html:16:12: executing "posts/single.html" at <partial "head/seo.html" .>: error calling partial: "/home/nimgus/blog/themes/uBlogger/layouts/partials/head/seo.html:130:25": execute of template failed: template: partials/head/seo.html:130:25: executing "partials/head/seo.html" at <index .Site.Data.authors $publisherName>: error calling index: index of untyped nil

### Build Environment

hugo v0.81.0-59D15C97+extended linux/amd64  VendorInfo=gohugoio
Theme version : 2.0.X

### Preview Environment

OS: Windows 10
Browser: Brave

### Additionnal informations

Maybe it could be related with the taxonomy error (pinned issue)

Thank you for your availability.

**Comment by uPagge** [comment]
This is not a bug. Find the params.version field in the config. And put 2.0.X

**Comment by Warsasor** [comment]
> This is not a bug. Find the params.version field in the config. And put 2.0.X

I would not have opened an issue if it was as easy as you say... I already did that and the site still unloading due to the probleme above.

**Comment by uPagge** [comment]
I apologize, I did not pay attention to the error, or rather it seemed that its essence was in changing the version

Apparently you do not have author.name set in config file.

![изображение](https://user-images.githubusercontent.com/40397740/110750735-f9d03380-8253-11eb-9c02-92ed4b677a0b.png)

**Comment by uPagge** [comment]
Although it seems to work without it. Another assumption, there is no data from the author

![изображение](https://user-images.githubusercontent.com/40397740/110750950-4b78be00-8254-11eb-9b10-4039dab1ec49.png)

**Comment by uPagge** [comment]
Although it seems to work for me without it all

**Comment by uPagge** [comment]
> Although it seems to work without it. Another assumption, there is no data from the author
> 
> ![изображение](https://user-images.githubusercontent.com/40397740/110750950-4b78be00-8254-11eb-9b10-4039dab1ec49.png)

Yes, that's the problem. If you do not want to specify the author, then for now it is sufficient to simply create the authors in data folder.

**Comment by uPagge** [comment]
@Warsasor Released fixes to master. Update should help

**Comment by Warsasor** [comment]
> @Warsasor Released fixes to master. Update should help

Thanks a lot for your replies and your reactivity. It works well again ! 
Quite a good resolution :D

**Comment by uPagge** [comment]
Glad I helped. If you find something else, write))
