### ISSUE TITLE
[BUG] Broken link in the documentation

### ISSUE THREAD

**Issue by EduSemensati** [uPagge/uBlogger#6]
### Intro (and thanks!)
First of all: thanks for picking up the old theme and keeping up the support on this repo. I have chosen it as my theme of choice for my personal website, which I am trying to setup right now.

This here is not much of a bug, more like a broken link in the documentation site! I found myself reading the demo site documentation and wanting to check the code in the repo, but...

### Describe the bug
When a user is reading the documentation at https://ublogger.netlify.app/ and click on the GitHub Icon to get to this repo, he/she is actually taken to https://github.com/upagge/dolboblog-theme, which servers a 404 Error page.

### Expected behavior
I would expect this link to take me to: https://github.com/uPagge/uBlogger

### Screenshots
![image](https://user-images.githubusercontent.com/24209506/103312217-a0aa7f00-4a1c-11eb-9581-e38281a08d5a.png)

**Comment by uPagge** [comment]
Hello again))

Oh, really. This was the working title :D

I will also fix it with the next update.

**Comment by uPagge** [comment]
Fixed in version 1.2.0
