### ISSUE TITLE
[BUG] echarts not defined

### ISSUE THREAD

**Issue by sebfischer83** [uPagge/uBlogger#60]
### Describe the bug

When using the echarts shortcode I get
theme.js:724 ReferenceError: echarts is not defined
    at theme.js:528
    at a.forEach (theme.js:4)
    at a._echartsOnSwitchTheme (theme.js:527)
    at a.initEcharts (theme.js:534)
    at a.init (theme.js:720)
    at HTMLDocument.themeInit (theme.js:740)
init @ theme.js:724
themeInit @ theme.js:740

### Expected behavior

The chart should appear.

### Build Environment

- OS: Windows 10
- Theme version/commit 2.0.1
- Hugo version  v0.78.2/extended

### Preview Environment

- OS: Windows 10
- Browser Chrome

**Comment by uPagge** [comment]
Yes, unfortunately something broke there. So far there was no time to see what.

**Comment by sebfischer83** [comment]
Hi, thanks for the answer. It works when I add echarts as a custom js.

**Comment by uPagge** [comment]
Strange, but I don't see any problems with echarts, everything is still available on the demo site.

There was a problem with css mermaid and I fixed it, but there seems to be no problem with echarts

**Comment by sebfischer83** [comment]
Strange indeed. I will look into it, maybe I found something. I noticed that the demo page works without problems. Thanks for your response. I will close it and notice you if I found something helpfull. Thanks for your work on the project!

**Comment by uPagge** [comment]
The only problem I have been able to find is as follows. If you run the hugo server locally, it may not be rendered at the first start, so that the graphs appear, you need to make some change to the md file. I don’t know yet what it’s connected with, but this problem is not observed during the final generation of the public folder.

**Comment by mij** [comment]
Try with the `--disableFastRender` argument when serving. This solved it for me:

```
hugo serve -D --disableFastRender
```

When building and deploying the static site, the problem does not occur by itself.
