### ISSUE TITLE
[BUG] open article in new window

### ISSUE THREAD

**Issue by dxball** [uPagge/uBlogger#62]
### Describe the bug

At homepage, click article title should open page in same window, but it opened in new window

### Expected behavior

open article in same window (browser tab)

### Build Environment

- OS: Win10
- Theme: 4e7b1fd
- Hugo version: 0.81.0

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: Win10
- Browser Chrome

### Additional Information

Configuration files or front matter code...

**Comment by uPagge** [comment]
As I said in a recent PR, this is not a bug, it is by design. I do not want the list of articles to close due to the opening of one of the articles.

Perhaps I will make an option in the config file in the next version, since there is such a demand for it

**Comment by dxball** [comment]
I think u should let user decide what behaviour they what use
I can open link in new tab by clicking middle button
