### ISSUE TITLE
[BUG] Update Screenshots in the Documentation

### ISSUE THREAD

**Issue by EduSemensati** [uPagge/uBlogger#7]
### Describe the bug
Since you have decided to rebrand the theme to uBlogger once you took over its maintenance, it would be good to update the documentation site as well, so it looks more professional ;)

### Expected behavior
I would expect that all screenshots in the documentation are using the name "uBlogger" instead of LoveIt.

### Screenshots
One example can be seen below. There might be others, but I have not gone through the whole docs yet 😋 

![image](https://user-images.githubusercontent.com/24209506/103313348-18c67400-4a20-11eb-8d90-651359687ad3.png)

**Comment by uPagge** [comment]
Hi

All that I found, I updated, apparently missed it.

I will fix it in the next update, thanks

**Comment by uPagge** [comment]
Fixed in version 1.2.0
