### ISSUE TITLE
[BUG] Avatar broken on every home page after page 1

### ISSUE THREAD

**Issue by evanaze** [uPagge/uBlogger#70]
### Describe the bug

The avatar image is broken and not displaying on pages after the first page in the home page.

### Expected behavior

I expect the avatar image to load on all pages of the home page.

### Screenshots

Here is the first page of my home page, with the avatar loading correctly:
<img width="1532" alt="Screen Shot 2021-03-26 at 9 33 30 AM" src="https://user-images.githubusercontent.com/25772568/112663780-75b2aa00-8e16-11eb-857b-1aa0cbcecd01.png">
Here is the second page, with the avatar broken:
<img width="1532" alt="Screen Shot 2021-03-26 at 9 33 35 AM" src="https://user-images.githubusercontent.com/25772568/112663827-806d3f00-8e16-11eb-9656-16b880ec20a7.png">

### Build Environment

- OS: MacOs
- Theme version/commit: I'm not sure how to find the theme version, maybe you can advise me on this, but it is 2.X.X.
- Hugo version [e.g. 0.69.0]: hugo v0.82.0+extended darwin/amd64 BuildDate=unknown

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: [e.g. Windows 10, macOS, Ubuntu, iOS, Android] MacOS. Bug is visible on preview and live server.
- Browser [e.g. Chrome, Safari, Firefox]: Brave and Safari

### Additional Information

Configuration files or front matter code...

**Comment by uPagge** [comment]
I do not have such a problem, so it is worth attaching either a minimal project illustrating the problem, or at least a configuration

**Comment by evanaze** [comment]
I figured out the issue. I had the avatarURL as "images/headshot.jpeg", and once I added the leading backslash and changed the file path to "/images/headshot.jpeg" it fixed the issue. Thanks!

**Comment by uPagge** [comment]
Yes, not at all, I'm glad you figured it out. You can contact with me any time
