### ISSUE TITLE
Several problems cannot be solved

### ISSUE THREAD

**Issue by xmoon5** [uPagge/uBlogger#71]
### Describe the bug
see image below

### Screenshots

![image](https://user-images.githubusercontent.com/61509470/112803275-b116d800-90a5-11eb-9c81-40e868b872d3.png)
![image](https://user-images.githubusercontent.com/61509470/112803447-dd325900-90a5-11eb-97c0-c211f54ac540.png)

### Description

1. I need to display `Moon` when the mouse is pointing at the image, not paths as `/images/avaters.png`.
2. I want the tabs to appear below, just like your blog
3. Author cannot display
4. The comment system is not working properly. I am using Valine

This is my blog: https://xmoon.info/

**Comment by xmoon5** [comment]
Now I have 3rd and 4th questions, and I want this template at the top of the article page
![image](https://user-images.githubusercontent.com/61509470/112834916-2cd74b80-90cb-11eb-86fb-4bf9d49e4614.png)

**Comment by xmoon5** [comment]
Theme=dark‘s [icon](static/img/icon/sprite-dark.svg) is abnormal
![image](https://user-images.githubusercontent.com/61509470/113249563-77d2a800-92f1-11eb-9739-7978455195f6.png)

**Comment by uPagge** [comment]
I did not have time to get acquainted with this issue, there was no time. Were you able to deal with your problems?
