### ISSUE TITLE
[BUG] Awesome Fonts from Google not working?

### ISSUE THREAD

**Issue by sspaeti** [uPagge/uBlogger#73]
### Describe the bug

Fontawesome from Google is not correctly set. Even though I set the `fontawesome = true`.

### Expected behaviour

If I set the above in my `config.toml` to `true`, I would expect to use something like this: `font-family: 'Open Sans', sans-serif;` in my CSS. But it didn't really use the Open Sans font.

### Build Environment

- OS: macOS
- Theme version/commit 0.2.2
- Hugo version hugo v0.82.0+extended darwin/amd64

### Additional Information

I could fix it with [this gist](https://gist.github.com/jeremybise/a6afea2d4c7f9044180ffeb663a617cf) by adding `{{- partial "google-fonts.html" . -}}` to my `baseof.html`. Should I create a PR, or will you add it directly? :-) Or did I do something wrong that didn't work before? I guess it's also not working on yours. Shouldn't these codes in Att. 1 also be some symbols or emojis?

PS: Thanks so much for your effort. I was searching for some templates until I found yours. I directly stopped searching! The features are amazing! I'm just moving now all my WordPress content over to Hugo and your template! Very much appreciated!!

Att. 1:
![image](https://user-images.githubusercontent.com/689199/113260158-3a105800-92ce-11eb-846c-8ea39860f1c2.png)

**Comment by uPagge** [comment]
![изображение](https://user-images.githubusercontent.com/40397740/113323040-24c31a00-931e-11eb-882c-52e3d9e69c1c.png)

**Comment by sspaeti** [comment]
Where is that print screen from? I only imported the font that I use like `["Open Sans", "300, 300i, 400, 400i, 600, 600i, 700, 700i, 800, 800i"]`. And I use it as my default meaning on every page. Therefore no need to deactivate. But I see your point, will check what will be the performance impact of it.
