### ISSUE TITLE
[BUG] Gitalk init error

### ISSUE THREAD

**Issue by long5778013** [uPagge/uBlogger#74]
### Describe the bug

When we need to authorize gitalk, the http get a 403 response.

![image](https://user-images.githubusercontent.com/10125514/113467669-218f7180-9477-11eb-8417-7d0f36b21da3.png)

### Expected behavior

The init process should get a 200 response.

### Solve
uBlogger need to upgrade the gitalk version to 1.7.2, and config the proxy to 'https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token'

### Build Environment

- OS: [e.g. macOS]
- Theme version/commit [e.g. 2.0.X]
- Hugo version [e.g. 0.69.0]

Please try to use Hugo **extended** version before opening the issue.

**Comment by uPagge** [comment]
Unfortunately I am not using gitlak, and only left it because it was in the original theme. Maybe someone from gitlak users can help

**Comment by long5778013** [comment]
Hi , I created a PR for this issue : https://github.com/uPagge/uBlogger/pull/129 @uPagge

**Comment by uPagge** [comment]
great news, thanks for your help 🙂
