### ISSUE TITLE
Markdown Syntax parsing error

### ISSUE THREAD

**Issue by xmoon5** [uPagge/uBlogger#75]
Syntax parsing error

markdown code：
`>[uBlogger](https://github.com/upagge/uBlogger) is a **clean**, **elegant** but **advanced** blog theme for [Hugo](https://gohugo.io/) developed by [uPagge](https://upagge.ru).`
`>`
`> It is based on the original [LeaveIt Theme](https://github.com/liuzc/LeaveIt) and [KeepIt Theme](https://github.com/Fastbyte01/KeepIt).`
it should be：

>[uBlogger](https://github.com/upagge/uBlogger) is a **clean**, **elegant** but **advanced** blog theme for [Hugo](https://gohugo.io/) developed by [uPagge](https://upagge.ru).
>
> It is based on the original [LeaveIt Theme](https://github.com/liuzc/LeaveIt) and [KeepIt Theme](https://github.com/Fastbyte01/KeepIt).

HTML:
![image](https://user-images.githubusercontent.com/61509470/113469469-3d4b4580-9480-11eb-8c8e-f05babf000dc.png)

I don't know how to deal with it

**Comment by uPagge** [comment]
In the next version, quotes will work as before.

**Comment by uPagge** [comment]
In master, the revised version
