### ISSUE TITLE
New images are not loading

### ISSUE THREAD

**Issue by rgrajan** [uPagge/uBlogger#76]
### Describe the bug

I am new to Hugo and I am trying to load an image in the header. Whatever the files I added is not showing up. But if i try the images already available in the theme, it's showing. Eg: lighthouse.jpg. I added the file in the static folder and also in the assets/images folder. It's not any permission issue. I tried for Avatar Url, there also same problem. I have the baseurl set to http://localhost:1313/ also.

### Expected behavior

The images added should show up but not showing.

### Screenshots

![image](https://user-images.githubusercontent.com/7380733/113494274-d1cf9b00-94b4-11eb-8f8a-dc6bb57187c5.png)

### Build Environment

- OS: Windows 10, WSL 2
- Theme version/commit 2.0.X
- Hugo version  v0.79.0/extended linux/amd64

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: Windows 10, WSL 2
- Browser FireFox, Edge

### Additional Information

I googled and tried troubleshooting but not sure what am i missing? or is this related to issues reported for 2.x version of this theme?

**Comment by Sp-cy** [comment]
with something like this:

``` 
  # Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # uBlogger NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "favicon-32x32.png"
      # title name
      name = ""
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
```

i get this: 
![image](https://user-images.githubusercontent.com/68587155/114887848-677cfb80-9dce-11eb-8833-0f662ed5b1d7.png)

img file is in static/

**Comment by rgrajan** [comment]
Thanks @Sp-cy. This is working.
