### ISSUE TITLE
[BUG] Zero card margin in homepage if post doesn't have a Tag

### ISSUE THREAD

**Issue by 50bhan** [uPagge/uBlogger#8]
### Describe the bug

if you don't define any tags for your post (or remove the tags key from your post config part), the margin between posts in HomePage turns to zero.

### Expected behavior

The normal margin between posts as usual.

### Screenshots

![Screenshot_2020-12-31_12-20-06](https://user-images.githubusercontent.com/36772278/103402856-4f58d780-4b63-11eb-8a37-612657192c0c.png)

### Build Environment

- OS: [Ubuntu]
- Theme version/commit [1.2.X]
- Hugo version [0.79]

**Comment by uPagge** [comment]
Hi

I will correct it in early January))
