### ISSUE TITLE
[DOCUMENTATION] How to create the ending post section?

### ISSUE THREAD

**Issue by hellt** [uPagge/uBlogger#80]
### Describe the feature you want

Hi @uPagge 
Could you please share with us how to create the section after the post, you have it on uPagge.ru

![image](https://user-images.githubusercontent.com/5679861/115233949-ce751a00-a118-11eb-9cb8-b308cb7cba93.png)

**Comment by uPagge** [comment]
It is better to write such questions in discussions. I transfer there
