### ISSUE TITLE
[BUG] 2.0.X -> 1.3.X: You have an incompatible update.

### ISSUE THREAD

**Issue by adelerhof** [uPagge/uBlogger#89]
### Describe the bug
When compiling a new site I get the error below while using Hugo version 0.83.1.
I matched the config.toml with the new version, what else should I change?
The content did not change with the theme version.

```
INFO 2021/05/04 16:41:21 Using config file: 
Start building sites … 
INFO 2021/05/04 16:41:21 syncing static files to /home/...
ERROR 2021/05/04 16:41:21 Compatibility Error 兼容性错误

2.0.X -> 1.3.X:
You have an incompatible update. See https://github.com/upagge/uBlogger/releases
你进行了一次不兼容的更新. 参考 https://github.com/upagge/uBlogger/releases

Total in 1537 ms
Error: Error building site: logged 1 error(s)
```

### Build Environment

- OS: alpine:3.12.2, Ubuntu
- Theme version/commit: 2.0.2
- Hugo version: Hugo extended 0.83.1

**Comment by farhan443** [comment]
>I matched the config.toml with the new version.

There are 2 things you should check:
1. Make sure you did that correctly. A correct example would be:
```
[params]
  version = "2.0.X"
```
2. Make sure that you're indeed using the latest version.

If you're certain that these two are not the issues, you may provide a screenshot / snippet of your config.toml and let us have a look.

**Comment by adelerhof** [comment]
> There are 2 things you should check:
> 
>     1. Make sure you did that correctly. A correct example would be:

```
[params]
  # uBlogger theme version
  version = "2.0.X"
```

>     2. Make sure that you're indeed using the latest version of the theme (v2.0.X).

I'm not sure where to find the version of the theme. I use it as submodule and did a git pull, also a new recursive clone `git clone --recursive git@github.com:` didn't do the trick.

> If you're certain that these two are not the issues, you may provide a screenshot / snippet of your config.toml and let us have a look.

[https://gist.github.com/adelerhof/3b66e12f9f45a6c2064c71b7420b3ec2](url)

**Comment by farhan443** [comment]
>https://gist.github.com/adelerhof/3b66e12f9f45a6c2064c71b7420b3ec2

Hmm, I didn't see anything wrong with your config.toml. So the problem might be the version of the theme you're using.

> I'm not sure where to find the version of the theme

There's a trick you can do to find the it. Navigate to your hugo folder > themes > uBlogger > exampleSite. There you can find a config.toml sample with the theme version. 

![uBlogger_sampleConfig](https://user-images.githubusercontent.com/77048921/117084422-660d7600-ad71-11eb-965b-6f6d5d038698.png)

**Comment by adelerhof** [comment]
I checked both examples, both have the correct version. I also tried an other version of Hugo (0.81.0) to make sure it wasn't a new Hugo bug, but that's gives no solution either.

**Comment by uPagge** [comment]
I didn't quite understand what you replaced to make it work. But this month I hope to update the documentation, which will describe the process of starting a site from scratch.
