### ISSUE TITLE
[BUG] Incorrect position of comment section and tags in posts

### ISSUE THREAD

**Issue by 50bhan** [uPagge/uBlogger#9]
### Describe the bug

When you open a post, the tags position and comment section are not in right place.

### Expected behavior

They should align in the center.

### Screenshots

![Screenshot_2020-12-31_14-57-09](https://user-images.githubusercontent.com/36772278/103408713-ee3bfe80-4b78-11eb-916a-32cf8bc9f202.png)

### Build Environment

- OS: [Ubuntu]
- Theme version/commit 1.2.X]
- Hugo version [0.79]

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: [Ubuntu]
- Browser [Chrome]
- Monitor Size and Resolution [30 inches - 2560 * 1080]

**Comment by whackerbeta** [comment]
I have the same problem with IE edge
