### ISSUE TITLE
[BUG] Slow build 

### ISSUE THREAD

**Issue by simm3531** [uPagge/uBlogger#90]
### Slow build 400 000 posts

With default settings, 400,000 posts from md files, about 2 kilobytes each, 40 categories in total, 5 tags The assembly takes over 24 hours. It seems that posts are generated quickly, but then pagination is very slow, etc. CPU usage ~70%, RAM ~55Gb

### Build Environment

- OS: Windows 10, Windows Server 2012R2
- Theme version 2.0.2
- Hugo version v0.82.0-9D960784+extended windows/amd64
- CPU: i7-8700k
- RAM: 64 Gb

**Comment by uPagge** [comment]
There is no way I can verify this without a test case.

**Comment by simm3531** [comment]
> 
> 
> There is no way I can verify this without a test case.

Hi. Test project in attach (25k pages). Thx
[test_site.zip](https://github.com/uPagge/uBlogger/files/6434211/test_site.zip)
![hugo_stats](https://user-images.githubusercontent.com/40929338/117295294-56c71f00-ae7c-11eb-8f56-dcc9c1bea5b0.jpg)

**Comment by uPagge** [comment]
I simplified the logic of the paginator and suppressed the caching of the particle in some places. Can you see if this helped?

**Comment by uPagge** [comment]
It doesn't seem to have helped much. I will add a limit on the number of pages in pagination

**Comment by simm3531** [comment]
Improve pagination performance https://github.com/gohugoio/hugo/pull/8602#issuecomment-852602819

**Comment by uPagge** [comment]
This is great news.

**Comment by simm3531** [comment]
https://github.com/gohugoio/hugo/releases/tag/v0.84.0

**Comment by uPagge** [comment]
@simm3531 Is everything good on the new version?

**Comment by simm3531** [comment]
> @simm3531 Is everything good on the new version?

With the default settings, the build speed has not increased for me, maybe I need to change something in the theme, I have not yet studied the point of the new release.

**Comment by uPagge** [comment]
> With the default settings, the build speed has not increased for me, maybe I need to change something in the theme, I have not yet studied the point of the new release.

I will be glad to have feedback if we can increase the speed.
